mail.mail_message.*:
  type: config_entity
  label: 'Mail message'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    group:
      type: string
      label: 'Group'
    subject:
      type: label
      label: 'Subject'
    body:
      type: text
      label: 'Body'
    message_processor:
      type: string
      label: 'ID of the Mail Message Processor plugin'
    mail_backend:
      type: string
      label: 'ID of the Mail Backend plugin'
    uuid:
      type: string
