<?php

/**
 * @file
 * Contains annonce.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function annonce_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the annonce module.
    case 'help.page.annonce':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('un module d&#039;annonce à la con') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function annonce_theme() {
  return [
    'annonce' => [
      'render element' => 'children',
    ],
  ];
}
