schema.settings:
  type: mapping
  label: Settings
  mapping:
    schema_database_connection:
      type: string
    schema_status_report:
      type: boolean
    schema_suppress_type_warnings:
      type: boolean
